const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const page=read('public/vape-durbanville.html'); const shop=read('public/bc10000/index.html'); const worker=read('src/worker.js'); const sitemap=read('public/sitemap.xml');
assert(page.includes('<title>Vape Durbanville | Disposable Vapes Cape Town | Vestige Vapes</title>'));
assert(page.includes('<link rel="canonical" href="https://vestigeltd.co.za/vape-durbanville"/>'));
assert(page.includes('<h1>Disposable Vapes in Durbanville</h1>'));
assert(page.includes('does not advertise a walk-in Durbanville storefront'));
assert(!page.includes('LocalBusiness'), 'Do not claim LocalBusiness without verified physical location');
assert(shop.includes('href="/vape-durbanville"'));
assert(shop.includes('Looking for disposable vapes in Durbanville?'));
assert(worker.includes("'/vape-durbanville': '/vape-durbanville.html'"));
assert(worker.includes("url.pathname === '/vape-durbanville.html'"));
assert(sitemap.includes('<loc>https://vestigeltd.co.za/vape-durbanville</loc>'));
const locs=[...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]); assert.equal(locs.filter(x=>x==='https://vestigeltd.co.za/vape-durbanville').length,1);
for(const forbidden of ['same-day delivery','walk-in store','physical store in Durbanville']) assert(!page.toLowerCase().includes(forbidden));
console.log('V35.26.11 Durbanville local SEO checks passed');
