'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'public','owner.html'),'utf8');
const js=fs.readFileSync(path.join(root,'public','owner.js'),'utf8');
const api=fs.readFileSync(path.join(root,'src','zoho-integration.cjs'),'utf8');
assert.match(html,/OPERATIONAL INVOICE REFERENCES/);
assert.match(html,/Test Order Housekeeping/);
assert.match(html,/Zoho Books invoices and payments are never changed/);
assert.match(js,/admin_preview_test_order_reset/);
assert.match(js,/admin_apply_test_order_reset/);
assert.match(js,/previewFingerprint/);
assert.match(api,/buildOwnerTestResetPlan/);
assert.match(api,/confirmationRequired/);
assert.match(api,/previewFingerprint/);
assert.match(api,/admin_test_order_reset/);
assert.match(api,/Zoho Books/);
assert.doesNotMatch(js,/sessionStorage\.setItem\([^\n]*admin/i);
console.log('V35.26.2 owner-housekeeping release safeguards passed.');
